import '../styles/globals.scss'
import 'bootstrap/dist/css/bootstrap.css'
import Head from 'next/head'
import type { AppProps } from 'next/app'

export default function MyApp({ Component, pageProps }: AppProps) {
    // return <Component {...pageProps} />
    return (
        <div className='root-app'>
            <Head>
                <title>NextJS</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Component {...pageProps} />
        </div>
    )
}

// export default MyApp
