import type { NextPage } from 'next'
import { useEffect, useState, useMemo, useRef } from 'react'
import { useRouter } from 'next/router'
import Link from "next/link";
import { Container, Row, Col, Nav } from 'react-bootstrap'
import useConstructor from './components/useConstructor';
import Header from './components/Header';
import Head from 'next/head'

const Index: NextPage = () => {
    return (
        <>
             <Head>
                 <title>NextJS</title>
                 <meta name="description" content="Generated by create next app" />
                 <link rel="icon" href="/favicon.ico" />
             </Head>
            <Header />
        </>
    )
}
export default Index
